# Meta data for the action.

name: 'Heroku Review App Deployment Status'
author: 'niteo.co'
description: 'A Github Action to test the deployment status of a Heroku Review App.'
branding:
  icon: 'git-pull-request'  
  color: 'orange'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  interval:
    description: Interval to check the status.
    required: false
    default: 10 # 10 seconds
  accepted_responses:
    description: Status(es) which can be accepted. Separated by comma.
    required: false
    default: 200 # All OK status
