# Meta data for the action.

name: 'Heroku Review App Deployment Status'
author: 'niteo.co'
description: 'A Github Action to test the deployment status of a Heroku Review App.'
branding:
  icon: 'git-pull-request'  
  color: 'orange'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  checks:
    description: Comma separated list of checks to perform.
    required: false
    # Default: Perform all checks
    default: build, response
  build_time_delay:
    description: Delay for the build stage of the review app.
    required: false
    default: 5
  load_time_delay:
    description: Delay for the app to load and start serving after it is built.
    required: false
    default: 5
  interval:
    description: Interval to repeat the deployment check in seconds.
    required: false
    default: 10
  accepted_responses:
    description: Comma separated status which can be accepted.
    required: false
    default: 200
  deployments_timeout:
    description: Maximum waiting time to fetch the deployments.
    required: false
    default: 120
